### ISSUE TITLE
CNS should always publish names for poseidon

### ISSUE THREAD

**Issue by coyhile** [joyent/triton-cns#14]
Similar to what is done for things owned by user `admin` in https://github.com/joyent/triton-cns/blob/master/lib/flag-filter.js#L187-L192 , CNS should publish names for instances owned by poseidon and for cmon in the same way as is done for adminui, cloudapi, etc today.

**Comment by coyhile** [comment]
@bahamat I think #16 addresses this.

**Comment by bahamat** [comment]
Fixed in #16
