### ISSUE TITLE
Mixed case DNS zones cause lookup failures, SERVFAIL for authoritative zones

### ISSUE THREAD

**Issue by bahamat** [joyent/triton-cns#18]
Reported by @bhechinger, a case where the Triton datacenter name contained an upper case character, cns would not return names on any of the zones, nor even return axfr requests. After quite a bit of debugging, I've tracked this down to not converting forward zones to lower case while doing `findZone()`.

**Comment by bhechinger** [comment]
The patch you provided me with works as expected, thanks!
