### ISSUE TITLE
No cns record for new container for cmon service. 

### ISSUE THREAD

**Issue by tangfeng123** [joyent/triton-cns#5]
I have deploy the cmon and cmon-agent in my env. and use the command line could discover and get the instance's informaiton successful.
but Below steps is not work for me.
Container Creation
User creates a new container
VMAPI pushes a changefeed event to CNS and the proxy
CNS creates CNAME records of the form
When I create a new container finished, There is no CNAME record created.
So in my promethues system, all the instance show down like below.
Get https://500250f3-833b-470f-ad2d-10c6464a7e8f.cmon.bst-1.bstjpc.com:9163/metrics: dial tcp: lookup 500250f3-833b-470f-ad2d-10c6464a7e8f.cmon.bst-1.bstjpc.com on 203.241.132.34:53: no such host

is it cause by the vmapi version too low?
this is my vmapi version
release-20161027-20161027T010017Z-gaf77e72

any comment is appreciate.

**Comment by arekinath** [comment]
What version of CNS are you running? CMON records were not working correctly until the early 2017 releases of CNS.

The next thing to check after that would be to look in the cns-updater logs for that VM uuid and see what the updater did.

**Comment by bahamat** [comment]
Closing this stale issue.
