### ISSUE TITLE
SRV records returns is not DNS safe?

### ISSUE THREAD

**Issue by Adel-Magebinary** [joyent/triton-cns#6]
$ triton instance tag set -w admin-test triton.cns.services=foo:1234
triton instance tag set: error (ValidationFailed): error adding tags: Invalid tag parameters
    tags: Invalid: "foo:1234" is not DNS safe

**Comment by bahamat** [comment]
This is [CNS-147](https://smartos.org/bugview/CNS-147). Vmapi still needs an update to resolve the issue.

**Comment by Adel-Magebinary** [comment]
I have upgrade the cns to the latest. And I can add tags like foo:1234 but there's still no SRV record when I dig?

**Comment by arekinath** [comment]
@Adel-Magebinary Sorry for the delayed response, but what name are you supplying to `dig`? The SRV records are created on the actual service name, so you would have to do `dig SRV foo.svc.user.cns.company.com` to see the records.

If they're still not there, it would be great if you could proceed to find the `cns-updater` log entries for the VM so we can see what's going on (how to do this is described in the CNS Operator Guide)

**Comment by Adel-Magebinary** [comment]
@arekinath , Yes! thanks. I found the SRV record.  Can you please let me know why it is on the svc level instead of foo.cns.company.com? Cheers.

**Comment by bahamat** [comment]
Closing. This was fully resolved some time ago.
