### ISSUE TITLE
Zone alias change

### ISSUE THREAD

**Issue by benjamin-bergia** [joyent/triton-cns#9]
Apparently, after updating the alias of a zone, CNS keep using the old alias.
Is there any way to force CNS to use the new alias?

**Comment by bahamat** [comment]
The quickest way would be to briefly disable cns, either [instance tags](https://github.com/joyent/triton-cns/blob/master/docs/metadata.md#instance-tags-vmapi) or [metadata](https://github.com/joyent/triton-cns/blob/master/docs/metadata.md#instance-metadata-vmapi).
